### ISSUE TITLE
Merkle Tree hashing throws Deno crypto error

### ISSUE THREAD

**Issue by JackWH** [dahlia/json-hash#5]
Hi there, thanks for a really useful package! 🙏

`canon.ts` and `digest.ts` are working great under Deno 1.41 on both macOS and Ubuntu. However, `merkle.ts` is failing on both platforms:

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    name: algorithm.name.toUpperCase(),
                         ^
    at normalizeAlgorithm (https://deno.land/std@0.120.0/crypto/mod.ts:277:26)
    at Object.digest (https://deno.land/std@0.120.0/crypto/mod.ts:168:32)
    at Function.deriveFrom (https://deno.land/x/json_hash@0.2.0/merkle.ts:75:40)
    at merkle (https://deno.land/x/json_hash@0.2.0/merkle.ts:301:27)
```

I'm just getting started with Deno so I'm not sure if the issue is in this package, or something in an upstream library. Let me know if I can provide any more info, thanks!

**Comment by dahlia** [comment]
Hmm… I guess it's due to the outdated std library?  Could you provide some test code to reproduce it?

**Comment by JackWH** [comment]
The example code in the README file reproduces it reliably for me. Save this as `merkle-tree.ts`, then use `deno run merkle-tree.ts` to throw the error:

```ts
import { MerkleHash, merkle } from "https://deno.land/x/json_hash/merkle.ts";
import { assert } from "https://deno.land/std/testing/asserts.ts";

const a: MerkleHash<"BLAKE3"> = await merkle("BLAKE3", [1, 2, 3]);
const b: MerkleHash<"BLAKE3"> = await merkle("BLAKE3", [
  await merkle("BLAKE3", 1),
  await merkle("BLAKE3", 2),
  await merkle("BLAKE3", 3),
]);
assert(a.equals(b));

const c: MerkleHash<"BLAKE3"> = await merkle(
  "BLAKE3",
  { foo: "bar", baz: [1, 2, 3] }
);
const d: MerkleHash<"BLAKE3"> = await merkle(
  "BLAKE3",
  { foo: await merkle("BLAKE3", "bar"), baz: a }
);
assert(c.equals(d));

const e = await merkle(c);
assert(e.equals(c));
```

**Comment by dahlia** [comment]
Oh, the example code has a type error!  The last two lines need to change like below:

```diff
--- merkle-tree.ts      2024-03-11 02:06:49
+++ merkle-tree2.ts     2024-03-11 02:06:58
@@ -19,5 +19,5 @@
 );
 assert(c.equals(d));

-const e = await merkle(c);
+const e = await merkle("BLAKE3", c);
 assert(e.equals(c));
```

**Comment by jackwh** [comment]
Thanks for clarifying that! (No wonder I missed it, I had `// @ts-nocheck` at the top of my test file... 🙈)
